### ISSUE TITLE
Wrong number of arguments after upgrading to Rails 4.1.10

### ISSUE THREAD

**Issue by baburdick** [albertosaurus/power_enum_2#10]
```
       ArgumentError:
         wrong number of arguments (1 for 0)
       # power_enum-2.8.0/lib/power_enum/reflection.rb:115:in `association_primary_key'
       # activerecord-4.1.10/lib/active_record/relation/predicate_builder.rb:64:in `expand'
       # activerecord-4.1.10/lib/active_record/relation/predicate_builder.rb:43:in `block in build_from_hash'
       # activerecord-4.1.10/lib/active_record/relation/predicate_builder.rb:21:in `each'
       # activerecord-4.1.10/lib/active_record/relation/predicate_builder.rb:21:in `build_from_hash'
       # activerecord-4.1.10/lib/active_record/relation/query_methods.rb:954:in `build_where'
       # activerecord-4.1.10/lib/active_record/relation/query_methods.rb:572:in `where!'
       # activerecord-4.1.10/lib/active_record/relation/query_methods.rb:559:in `where'
       # activerecord-4.1.10/lib/active_record/querying.rb:10:in `where'
```

**Comment by baburdick** [comment]
`ActiveRecord::PredicateBuilder::expand` now passes a `base_class` (https://github.com/rails/rails/blob/v4.1.10/activerecord/lib/active_record/relation/predicate_builder.rb#L64) derived from the `value` (`base_class = polymorphic_base_class_from_value(value)`).

**Comment by baburdick** [comment]
This is the definition of `AssociationReflection#association_primary_key`: (https://github.com/rails/rails/blob/v4.1.10/activerecord/lib/active_record/reflection.rb#L271)
```ruby
      # klass option is necessary to support loading polymorphic associations
      def association_primary_key(klass = nil)
        options[:primary_key] || primary_key(klass || self.klass)
      end
```
And this is the definition of `ThroughReflection#association_primary_key`: (https://github.com/rails/rails/blob/v4.1.10/activerecord/lib/active_record/reflection.rb#L637)
```ruby
      # We want to use the klass from this reflection, rather than just delegate straight to
      # the source_reflection, because the source_reflection may be polymorphic. We still
      # need to respect the source_reflection's :primary_key option, though.
      def association_primary_key(klass = nil)
        # Get the "actual" source reflection if the immediate source reflection has a
        # source reflection itself
        actual_source_reflection.options[:primary_key] || primary_key(klass || self.klass)
      end
```
They've been like that for a few years. So it's just been lucky that no calls passed a `base_class` to it in that time. Based on this, the solution may just be to copy the method signature.

**Comment by baburdick** [comment]
Confirmed that that fixes the issue. PR coming ...
